import type { SvgIconComponent } from '@mui/icons-material';
import {
  AdminPanelSettingsOutlined,
  AnalyticsOutlined,
  ArticleOutlined,
  AssessmentOutlined,
  BarChartOutlined,
  BusinessOutlined,
  CheckCircleOutline,
  CheckCircleOutlined,
  CompareArrowsOutlined,
  DashboardOutlined,
  DescriptionOutlined,
  EditOutlined,
  ErrorOutline,
  ExtensionOutlined,
  FolderOutlined,
  HelpOutline,
  HistoryOutlined,
  HubOutlined,
  Inventory2Outlined,
  InventoryOutlined,
  LightbulbOutlined,
  LocalShippingOutlined,
  MapOutlined,
  MenuBookOutlined,
  PeopleOutlined,
  PlayCircleOutline,
  ReceiptLongOutlined,
  ReportProblemOutlined,
  RouteOutlined,
  ScienceOutlined,
  SettingsOutlined,
  ShieldOutlined,
  SpeedOutlined,
  StoreOutlined,
  TrendingUpOutlined,
  TuneOutlined,
  ViewInArOutlined,
  WarningAmberOutlined,
  WarehouseOutlined,
} from '@mui/icons-material';

const ICON_REGISTRY: Record<string, SvgIconComponent> = {
  FolderOutlined,
  EditOutlined,
  TuneOutlined,
  PlayCircleOutline,
  ViewInArOutlined,
  BarChartOutlined,
  CompareArrowsOutlined,
  DescriptionOutlined,
  ArticleOutlined,
  SettingsOutlined,
  CheckCircleOutline,
  CheckCircleOutlined,
  ErrorOutline,
  DashboardOutlined,
  HubOutlined,
  StoreOutlined,
  LocalShippingOutlined,
  ShieldOutlined,
  TrendingUpOutlined,
  InventoryOutlined,
  WarehouseOutlined,
  RouteOutlined,
  Inventory2Outlined,
  MapOutlined,
  WarningAmberOutlined,
  ReportProblemOutlined,
  AnalyticsOutlined,
  SpeedOutlined,
  ScienceOutlined,
  LightbulbOutlined,
  AssessmentOutlined,
  PeopleOutlined,
  AdminPanelSettingsOutlined,
  BusinessOutlined,
  ExtensionOutlined,
  MenuBookOutlined,
  HistoryOutlined,
  ReceiptLongOutlined,
};

export function getIcon(name: string): SvgIconComponent {
  return ICON_REGISTRY[name] ?? HelpOutline;
}
