from __future__ import annotations

from enum import Enum


class StrEnum(str, Enum):
    pass


class OrganizationType(StrEnum):
    CUSTOMER = "CUSTOMER"
    SUPPLIER = "SUPPLIER"
    CARRIER = "CARRIER"
    PLATFORM = "PLATFORM"


class WorkspaceType(StrEnum):
    INTERNAL = "INTERNAL"
    ADMIN = "ADMIN"
    SUPPLIER = "SUPPLIER"
    CARRIER = "CARRIER"


class AppRole(StrEnum):
    ADMIN = "ADMIN"
    SUPPLY_CHAIN_MANAGER = "SUPPLY_CHAIN_MANAGER"
    SUPPLY_PLANNER = "SUPPLY_PLANNER"
    LOGISTICS_MANAGER = "LOGISTICS_MANAGER"
    ANALYST = "ANALYST"
    SUPPLIER = "SUPPLIER"
    CARRIER = "CARRIER"


class NetworkNodeType(StrEnum):
    SUPPLIER = "SUPPLIER"
    FACTORY = "FACTORY"
    WAREHOUSE = "WAREHOUSE"
    DISTRIBUTION_CENTER = "DISTRIBUTION_CENTER"
    HUB = "HUB"
    CUSTOMER = "CUSTOMER"


class ConnectionType(StrEnum):
    TRANSPORT_LANE = "TRANSPORT_LANE"


class EntityStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    SUSPENDED = "SUSPENDED"


class RiskStatus(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ShipmentStatus(StrEnum):
    DRAFT = "DRAFT"
    PLANNED = "PLANNED"
    ASSIGNED = "ASSIGNED"
    ACCEPTED = "ACCEPTED"
    READY_FOR_PICKUP = "READY_FOR_PICKUP"
    IN_TRANSIT = "IN_TRANSIT"
    ARRIVED = "ARRIVED"
    DELIVERED = "DELIVERED"
    CANCELLED = "CANCELLED"


class ShipmentEventType(StrEnum):
    CREATED = "CREATED"
    ASSIGNED = "ASSIGNED"
    ACCEPTED = "ACCEPTED"
    PICKED_UP = "PICKED_UP"
    IN_TRANSIT = "IN_TRANSIT"
    ETA_UPDATED = "ETA_UPDATED"
    DELAY_REPORTED = "DELAY_REPORTED"
    EXCEPTION_CREATED = "EXCEPTION_CREATED"
    ARRIVED = "ARRIVED"
    DELIVERED = "DELIVERED"
    CANCELLED = "CANCELLED"


class ExceptionType(StrEnum):
    LATE_PICKUP = "LATE_PICKUP"
    LATE_DELIVERY = "LATE_DELIVERY"
    ETA_RISK = "ETA_RISK"
    VEHICLE_STOP = "VEHICLE_STOP"
    ROUTE_DEVIATION = "ROUTE_DEVIATION"
    NO_TRACKING = "NO_TRACKING"
    SUPPLIER_DELAY = "SUPPLIER_DELAY"
    CAPACITY_SHORTAGE = "CAPACITY_SHORTAGE"
    INVENTORY_RISK = "INVENTORY_RISK"
    SLA_RISK = "SLA_RISK"
    DATA_ISSUE = "DATA_ISSUE"


class ExceptionStatus(StrEnum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class IncidentStatus(StrEnum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    WAITING_PARTNER = "WAITING_PARTNER"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class PlanStatus(StrEnum):
    DRAFT = "DRAFT"
    CALCULATED = "CALCULATED"
    REVIEW = "REVIEW"
    APPROVED = "APPROVED"
    ACTIVE = "ACTIVE"
    SUPERSEDED = "SUPERSEDED"


class JobStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class DocumentType(StrEnum):
    INVOICE = "INVOICE"
    DELIVERY_NOTE = "DELIVERY_NOTE"
    POD = "POD"
    ASN = "ASN"
    CUSTOMS = "CUSTOMS"
    OTHER = "OTHER"


class ScenarioParameterCategory(StrEnum):
    DEMAND = "DEMAND"
    SUPPLIER = "SUPPLIER"
    CARRIER = "CARRIER"
    ROUTE = "ROUTE"
    WAREHOUSE = "WAREHOUSE"
    INVENTORY = "INVENTORY"


class NotificationType(StrEnum):
    NEW_EXCEPTION = "NEW_EXCEPTION"
    SHIPMENT_DELAYED = "SHIPMENT_DELAYED"
    INCIDENT_ASSIGNED = "INCIDENT_ASSIGNED"
    CARRIER_REPLY = "CARRIER_REPLY"
    PLAN_REVIEW_REQUIRED = "PLAN_REVIEW_REQUIRED"
    PLAN_APPROVED = "PLAN_APPROVED"
    SCENARIO_COMPLETED = "SCENARIO_COMPLETED"


class SemanticStatus(StrEnum):
    BEST = "BEST"
    RISK = "RISK"
    TARGET_REACHED = "TARGET_REACHED"
    TARGET_NOT_REACHED = "TARGET_NOT_REACHED"
    RECOMMENDED = "RECOMMENDED"
    SUCCESS = "SUCCESS"
    WARNING = "WARNING"
    NORMAL = "NORMAL"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    LOW = "LOW"
